### ISSUE TITLE
Project Profile: Volunteer modal window text vanish upon clicking submit

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#558]
On the project profile page, when acting upon a modal that has a text field and clicking submit, the modal text disappears while the operation completes, giving the impression that the operation has failed even when it has succeeded.

## TODO ##
- [ ] Disable Confirm button after clicking
- [ ] Don't clear modal text

## Applicable Project Operations ##
- [ ] Volunteer Leave Project
- [ ] Project Owner Dismisses Volunteer
- [ ] Project Owner Rejects Volunteer Application
- [ ] Project Owner Demotes Co-Owner

![LeaveProjectConfirmBehavior](https://user-images.githubusercontent.com/322346/111006859-69245100-8342-11eb-9ee2-9852ef2220d0.gif)
