### ISSUE TITLE
Project Profile: Volunteer modal confirm button doesn't visibly register click

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#559]
On the project profile page, when confirming certain volunteer action, the confirm button does not change after being clicked, not communicating that an action has been initiated, and giving the impression that nothing has happened.

## TODO ##
- [ ] Disable confirmation button after clicking

## Applicable Project Operations ##
- [ ] Project Owner Approves Volunteer
- [ ] Project Owner Promotes volunteer to Co-Owner

![ApproveVolunteerConfirmBehavior](https://user-images.githubusercontent.com/322346/111009182-c2db4a00-8347-11eb-9807-a27fed8cf199.gif)
