### ISSUE TITLE
Update Python to version supported by heroku

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#955]
When deploying to heroku, the deployment fails with the following message: 

-----> Using Python version specified in runtime.txt
 !     
 !     Python 3.6 reached upstream end-of-life on December 23rd, 2021, and is
 !     therefore no longer receiving security updates:
 !     https://devguide.python.org/versions/#supported-versions
 !     
 !     As such, it is no longer supported by the latest version of this buildpack.
 !     
 !     Please upgrade to a newer Python version. See:
 !     https://devcenter.heroku.com/articles/python-runtimes
 !     
 !     Push rejected, failed to compile Python app.
 !     Push failed

## TODO

- [ ] Update [requirements.txt](https://github.com/DemocracyLab/CivicTechExchange/blob/51acfdd51ad0339348e638ab39f63a06a76a5573/requirements.txt) with python version 10.10 or higher (see https://devcenter.heroku.com/articles/python-support#supported-runtimes)
- [ ] Update [docker config](https://github.com/DemocracyLab/CivicTechExchange/blob/51acfdd51ad0339348e638ab39f63a06a76a5573/Dockerfile) with docker image that has the new python version
- [ ] Create new VirtualBox VM image that uses the new python version
