### ISSUE TITLE
Upgrade heroku stack to Ubuntu 22

### ISSUE THREAD

**Issue by marlonkeating** [DemocracyLab/CivicTechExchange#956]
The current stack we're using, version 18, will be fully deprecated by 5/1/2023, and so we should update to the latest version.

https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq
https://devcenter.heroku.com/articles/stack#stack-support-details

## Prerequisites
- [ ] https://github.com/DemocracyLab/CivicTechExchange/issues/955

## TODO

- [ ] Update [docker config](https://github.com/DemocracyLab/CivicTechExchange/blob/51acfdd51ad0339348e638ab39f63a06a76a5573/Dockerfile) with docker image that has the python/node versions that match Ubuntu 22
- [ ] Create new VirtualBox VM image that uses Ubuntu 22
